export type SopEntry = {
  code: string;
  title: string;
  section: string;
  printedPage: number;
  keywords: string[];
};

export const SOP_ENTRIES: SopEntry[] = [
  // ── SOP 1: General Administration ──────────────────────────────────────────
  { code: "SOP 1", title: "General Administration", section: "General Administration", printedPage: 11, keywords: ["administration", "general", "sop 1"] },
  { code: "SOP 1.2", title: "Uniforms and Personal Hygiene", section: "General Administration", printedPage: 13, keywords: ["uniform", "hygiene", "personal hygiene", "dress code", "rank"] },
  { code: "SOP 1.3", title: "Leave and Shift Swops", section: "General Administration", printedPage: 17, keywords: ["leave", "shift swap", "shift swop", "annual leave", "off duty"] },
  { code: "SOP 1.5", title: "Red Rules in Ambulance Service", section: "General Administration", printedPage: 20, keywords: ["red rules", "rules", "regulations", "disciplinary"] },
  { code: "SOP 1.6", title: "Sanctions for Violating Rules and Regulations and Acts of Negligent Behavior", section: "General Administration", printedPage: 23, keywords: ["sanctions", "violations", "negligence", "disciplinary action"] },
  { code: "SOP 1.7", title: "Ambulances Driven by Non-Medical Personnel", section: "General Administration", printedPage: 24, keywords: ["non-medical", "driver", "ambulance driver", "non clinical"] },
  { code: "SOP 1.8", title: "Vehicles Running During Summer Season", section: "General Administration", printedPage: 25, keywords: ["summer", "vehicles", "heat", "running vehicles"] },
  { code: "SOP 1.9", title: "Unmarked Rapid Response Vehicle (RRV) Allocation", section: "General Administration", printedPage: 27, keywords: ["rrv", "rapid response", "unmarked", "vehicle allocation"] },
  { code: "SOP 1.11", title: "Photo/Video Recording", section: "General Administration", printedPage: 28, keywords: ["photo", "video", "recording", "photography", "social media"] },
  { code: "SOP 1.12", title: "WOQOD e-Fueling System", section: "General Administration", printedPage: 29, keywords: ["woqod", "fuel", "fueling", "petrol", "e-fuel"] },
  { code: "SOP 1.13", title: "Management Notification Process", section: "General Administration", printedPage: 30, keywords: ["notification", "management", "escalation", "reporting"] },
  { code: "SOP 1.14", title: "Absenteeism Management", section: "General Administration", printedPage: 32, keywords: ["absenteeism", "absence", "sick leave", "attendance"] },
  { code: "SOP 1.15", title: "Performance Improvement Process", section: "General Administration", printedPage: 41, keywords: ["performance", "improvement", "pip", "appraisal"] },
  { code: "SOP 1.16", title: "HMCAS Procurement and Contract Process", section: "General Administration", printedPage: 44, keywords: ["procurement", "contract", "purchasing", "supplies"] },
  { code: "SOP 1.17", title: "Disclosure of HMCAS Staff Identification to External Security Agencies", section: "General Administration", printedPage: 50, keywords: ["disclosure", "identification", "security agencies", "id", "police"] },
  { code: "SOP 1.19", title: "Conducting a Quality Improvement Activity in HMCAS", section: "General Administration", printedPage: 52, keywords: ["quality improvement", "qi", "audit", "improvement activity"] },

  // ── SOP 2: Health, Safety & Security ────────────────────────────────────────
  { code: "SOP 2", title: "Health, Safety, & Security", section: "Health Safety Security", printedPage: 60, keywords: ["health", "safety", "security", "hss", "sop 2"] },
  { code: "SOP 2.1", title: "Personal Protection & Safety", section: "Health Safety Security", printedPage: 62, keywords: ["ppe", "personal protection", "safety", "protective equipment"] },
  { code: "SOP 2.1.A", title: "Management of Ambulance in the Event of Fire", section: "Health Safety Security", printedPage: 66, keywords: ["fire", "ambulance fire", "fire management", "emergency"] },
  { code: "SOP 2.2", title: "Medical Waste Handling", section: "Health Safety Security", printedPage: 68, keywords: ["waste", "medical waste", "sharps", "biohazard", "disposal"] },
  { code: "SOP 2.3", title: "Social Cleaning and Simple Decontamination of Vehicles and Non-Critical Equipment", section: "Health Safety Security", printedPage: 71, keywords: ["cleaning", "decontamination", "vehicle cleaning", "disinfection"] },
  { code: "SOP 2.3.A", title: "Maintenance and Cleaning of HMCAS Response and Medication Bags", section: "Health Safety Security", printedPage: 73, keywords: ["medication bag", "drug bag", "cleaning", "response bag"] },
  { code: "SOP 2.3.B", title: "Infection Control in HMCAS Supply Chain", section: "Health Safety Security", printedPage: 75, keywords: ["infection control", "supply chain", "ipc"] },
  { code: "SOP 2.4", title: "Deep Cleaning of Patient Transporting Vehicles", section: "Health Safety Security", printedPage: 81, keywords: ["deep clean", "vehicle", "ambulance cleaning", "decontamination"] },
  { code: "SOP 2.5", title: "Management of Occupational Exposure to Blood and Body Fluids", section: "Health Safety Security", printedPage: 84, keywords: ["needlestick", "blood exposure", "body fluids", "occupational exposure", "sharps injury"] },
  { code: "SOP 2.6", title: "Oxygen Management by Ambulance Services", section: "Health Safety Security", printedPage: 86, keywords: ["oxygen", "o2", "cylinder", "oxygen management"] },
  { code: "SOP 2.7", title: "Security of Facilities, Vehicles and Equipment", section: "Health Safety Security", printedPage: 90, keywords: ["security", "facilities", "vehicles", "equipment security"] },
  { code: "SOP 2.7.A", title: "Use of Spoke and Hub Facilities", section: "Health Safety Security", printedPage: 92, keywords: ["hub", "spoke", "station", "facilities"] },
  { code: "SOP 2.7.B", title: "Helipad Base Security", section: "Health Safety Security", printedPage: 93, keywords: ["helipad", "helicopter", "base security", "lifeflight"] },
  { code: "SOP 2.7.C", title: "Traka Key Management System", section: "Health Safety Security", printedPage: 95, keywords: ["traka", "keys", "key management", "vehicle keys"] },
  { code: "SOP 2.8", title: "Use of Tobacco Products", section: "Health Safety Security", printedPage: 99, keywords: ["tobacco", "smoking", "vaping", "cigarette"] },
  { code: "SOP 2.9", title: "Fitness to Operate", section: "Health Safety Security", printedPage: 100, keywords: ["fitness", "fit for duty", "fitness to operate", "impairment"] },
  { code: "SOP 2.10", title: "Ambulance Service Fatigue Management", section: "Health Safety Security", printedPage: 102, keywords: ["fatigue", "tiredness", "fatigue management", "rest"] },
  { code: "SOP 2.11", title: "Workplace Violence", section: "Health Safety Security", printedPage: 105, keywords: ["violence", "workplace violence", "aggression", "assault"] },
  { code: "SOP 2.12", title: "Hand Hygiene", section: "Health Safety Security", printedPage: 106, keywords: ["hand hygiene", "handwashing", "infection control", "sanitiser"] },

  // ── SOP 3: Communications ────────────────────────────────────────────────────
  { code: "SOP 3", title: "Communications", section: "Communications", printedPage: 112, keywords: ["communications", "comms", "ncc", "dispatch", "sop 3"] },
  { code: "SOP 3.1", title: "NCC Call Routing", section: "Communications", printedPage: 114, keywords: ["ncc", "call routing", "dispatch", "national command center"] },
  { code: "SOP 3.2", title: "NCC Call Taking", section: "Communications", printedPage: 117, keywords: ["ncc", "call taking", "call taker", "999", "emergency call"] },
  { code: "SOP 3.3", title: "NCC Call Dispatching", section: "Communications", printedPage: 124, keywords: ["dispatching", "dispatch", "ncc", "call dispatch"] },
  { code: "SOP 3.4", title: "Obvious Death, Expected Death & Pre-Arrival CPR Instructions", section: "Communications", printedPage: 128, keywords: ["obvious death", "expected death", "pre-arrival cpr", "death", "cpr instructions", "caller instructions"] },
  { code: "SOP 3.5", title: "First Party Caller (Patient) Not Found on Arrival", section: "Communications", printedPage: 130, keywords: ["not found", "patient not found", "first party caller", "nfa"] },
  { code: "SOP 3.6", title: "High Risk Pregnancy Complications", section: "Communications", printedPage: 132, keywords: ["pregnancy", "obstetric", "high risk", "maternity", "labour"] },
  { code: "SOP 3.7.A", title: "The Emergency Rule", section: "Communications", printedPage: 134, keywords: ["emergency rule", "rule", "emergency dispatch"] },
  { code: "SOP 3.8", title: "Dispatching with Mobile Data Terminals", section: "Communications", printedPage: 135, keywords: ["mdt", "mobile data terminal", "tablet", "dispatch"] },
  { code: "SOP 3.9", title: "Daily Operations in the Communications Centres", section: "Communications", printedPage: 136, keywords: ["daily operations", "communications centre", "ncc", "hcc"] },
  { code: "SOP 3.10", title: "Telephone System Failure", section: "Communications", printedPage: 139, keywords: ["telephone failure", "phone system", "system failure", "downtime"] },
  { code: "SOP 3.11", title: "Radio System Failure", section: "Communications", printedPage: 142, keywords: ["radio failure", "radio system", "comms failure", "communication failure"] },
  { code: "SOP 3.12", title: "NJM Shutdown", section: "Communications", printedPage: 146, keywords: ["njm", "shutdown", "system shutdown"] },
  { code: "SOP 3.13", title: "Access to The Healthcare Coordination Center (HCC)", section: "Communications", printedPage: 151, keywords: ["hcc", "healthcare coordination", "access", "coordination center"] },
  { code: "SOP 3.14", title: "Call-For-Service Coordination Between NCC and HCC", section: "Communications", printedPage: 152, keywords: ["call for service", "ncc", "hcc", "coordination", "cfs"] },
  { code: "SOP 3.15", title: "Capturing Unit Status in MDT", section: "Communications", printedPage: 156, keywords: ["unit status", "mdt", "status", "available", "on scene"] },
  { code: "SOP 3.16", title: "Major Incident Response On Call Phones", section: "Communications", printedPage: 165, keywords: ["major incident", "on call", "mir", "phones"] },
  { code: "SOP 3.17", title: "Management of Call Sign Communications Equipment Sets (CCES)", section: "Communications", printedPage: 166, keywords: ["call sign", "cces", "radio", "communications equipment"] },
  { code: "SOP 3.18", title: "CareMonX CAD Shutdown", section: "Communications", printedPage: 171, keywords: ["caremonx", "cad", "shutdown", "computer aided dispatch"] },
  { code: "SOP 3.19.A", title: "NCC Evacuation Plan", section: "Communications", printedPage: 174, keywords: ["ncc", "evacuation", "evacuation plan"] },
  { code: "SOP 3.19.B", title: "HCC Evacuation Plan", section: "Communications", printedPage: 178, keywords: ["hcc", "evacuation", "evacuation plan"] },
  { code: "SOP 3.20", title: "Customer Service Communications For Healthcare Coordination Service Call Centers", section: "Communications", printedPage: 183, keywords: ["customer service", "hcc", "call center", "patient communication"] },
  { code: "SOP 3.21", title: "HCC Call Routing", section: "Communications", printedPage: 192, keywords: ["hcc", "call routing", "healthcare coordination"] },
  { code: "SOP 3.22", title: "HCC Call Taking", section: "Communications", printedPage: 198, keywords: ["hcc", "call taking", "healthcare coordination"] },
  { code: "SOP 3.23", title: "HCC Call Dispatching", section: "Communications", printedPage: 205, keywords: ["hcc", "dispatching", "healthcare coordination"] },
  { code: "SOP 3.24", title: "Managing Offshore Calls at NCC", section: "Communications", printedPage: 210, keywords: ["offshore", "ncc", "offshore calls", "maritime"] },
  { code: "SOP 3.26", title: "HMCAS Information Systems On Call", section: "Communications", printedPage: 213, keywords: ["it", "information systems", "on call", "it support"] },
  { code: "SOP 3.27", title: "EMD Certification", section: "Communications", printedPage: 215, keywords: ["emd", "emergency medical dispatch", "certification", "dispatch certification"] },
  { code: "SOP 3.28", title: "IT Equipment Allocation and Use", section: "Communications", printedPage: 218, keywords: ["it equipment", "computers", "tablets", "allocation"] },
  { code: "SOP 3.29", title: "DHP and Training Requirements for Ambulance Service Medical Dispatchers", section: "Communications", printedPage: 223, keywords: ["dhp", "training", "medical dispatcher", "dispatcher"] },
  { code: "SOP 3.30", title: "Handling Participant Cases", section: "Communications", printedPage: 229, keywords: ["participant", "vip", "participant cases", "special cases"] },

  // ── SOP 4: Emergency Operations ─────────────────────────────────────────────
  { code: "SOP 4", title: "Emergency Operations", section: "Emergency Operations", printedPage: 232, keywords: ["emergency operations", "operations", "sop 4"] },
  { code: "SOP 4.1.A", title: "Patient & Family Rights – Consent, Privacy & Confidentiality", section: "Emergency Operations", printedPage: 234, keywords: ["consent", "patient rights", "privacy", "confidentiality", "family rights"] },
  { code: "SOP 4.1.B", title: "Abuse and Neglect of Children and Adults", section: "Emergency Operations", printedPage: 237, keywords: ["abuse", "neglect", "child protection", "safeguarding", "domestic violence"] },
  { code: "SOP 4.1.C", title: "Confirmation of DHP Qualifications of Clinical Escorts and First Responders", section: "Emergency Operations", printedPage: 238, keywords: ["dhp", "qualifications", "clinical escort", "first responder", "credentials"] },
  { code: "SOP 4.2", title: "Shift Handover, Vehicle Check & Safety", section: "Emergency Operations", printedPage: 240, keywords: ["shift handover", "vehicle check", "handover", "safety check"] },
  { code: "SOP 4.2.A", title: "Routine Operational Shift Handover Vehicle Checking", section: "Emergency Operations", printedPage: 242, keywords: ["vehicle check", "shift handover", "routine check", "daily check"] },
  { code: "SOP 4.2.B", title: "Non-Routine Operational and Non-Operational Service Vehicle Checking", section: "Emergency Operations", printedPage: 244, keywords: ["non-routine", "vehicle check", "non-operational"] },
  { code: "SOP 4.3", title: "Medical Equipment & Medication Management", section: "Emergency Operations", printedPage: 247, keywords: ["medication", "equipment", "drug management", "controlled drugs", "medications"] },
  { code: "SOP 4.3.A", title: "Issuing & Maintenance of Medical Equipment & Supplies", section: "Emergency Operations", printedPage: 249, keywords: ["equipment issuing", "medical supplies", "maintenance", "stock"] },
  { code: "SOP 4.3.B", title: "Management of Non-Controlled Medications by Ambulance Paramedics & CCPs", section: "Emergency Operations", printedPage: 250, keywords: ["non-controlled", "medications", "drugs", "ap", "ccp", "paramedic drugs"] },
  { code: "SOP 4.3.C", title: "Controlled Medicines Management by Critical Care Paramedics", section: "Emergency Operations", printedPage: 251, keywords: ["controlled drugs", "controlled medicines", "ccp", "morphine", "fentanyl", "ketamine"] },
  { code: "SOP 4.3.D", title: "Near Patient Blood Testing", section: "Emergency Operations", printedPage: 254, keywords: ["blood test", "near patient", "poct", "glucose", "lactate", "blood testing"] },
  { code: "SOP 4.3.E", title: "High Alert and Look Alike Sound Alike Medications", section: "Emergency Operations", printedPage: 258, keywords: ["high alert", "lasa", "look alike", "sound alike", "medication safety"] },
  { code: "SOP 4.3.F", title: "Administration of High Alert and Look-Alike and Sound Alike Medication", section: "Emergency Operations", printedPage: 262, keywords: ["high alert", "lasa", "administration", "medication error", "safety"] },
  { code: "SOP 4.3.G", title: "LP15 Transmission Guidelines", section: "Emergency Operations", printedPage: 264, keywords: ["lp15", "lifepak", "ecg transmission", "transmission", "12 lead"] },
  { code: "SOP 4.3.G.1", title: "ZOLL X Transmission Guidelines", section: "Emergency Operations", printedPage: 266, keywords: ["zoll", "zoll x series", "ecg", "transmission", "defibrillator"] },
  { code: "SOP 4.3.H", title: "Discarding Paracetamol and Ibuprofen Syrup", section: "Emergency Operations", printedPage: 268, keywords: ["paracetamol", "ibuprofen", "syrup", "disposal", "discard"] },
  { code: "SOP 4.3.I", title: "Selecting Ambulance Service Medications and Equipment", section: "Emergency Operations", printedPage: 269, keywords: ["selecting", "medications", "equipment selection", "drug selection"] },
  { code: "SOP 4.3.J", title: "Air Lifting and Moving Devices", section: "Emergency Operations", printedPage: 270, keywords: ["air lifting", "moving devices", "lifting", "bariatric", "patient moving"] },
  { code: "SOP 4.3.K", title: "Transporting HMCAS Medications and Staff Travelling During Duty", section: "Emergency Operations", printedPage: 276, keywords: ["transporting medications", "medications transport", "staff travel", "duty travel"] },
  { code: "SOP 4.4", title: "Emergency Unit Distribution - Hub and Spoke Model", section: "Emergency Operations", printedPage: 277, keywords: ["hub spoke", "unit distribution", "deployment", "posting", "hub"] },
  { code: "SOP 4.5", title: "Emergency Unit Activation", section: "Emergency Operations", printedPage: 280, keywords: ["unit activation", "activation", "emergency unit", "dispatch activation"] },
  { code: "SOP 4.5.A", title: "Activation Via Control Centre", section: "Emergency Operations", printedPage: 282, keywords: ["activation", "control centre", "ncc", "dispatch"] },
  { code: "SOP 4.5.B", title: "Non-Control Centre Activation", section: "Emergency Operations", printedPage: 284, keywords: ["non-control centre", "activation", "self dispatch", "direct activation"] },
  { code: "SOP 4.5.C", title: "Radio Communication & Reporting", section: "Emergency Operations", printedPage: 285, keywords: ["radio", "communication", "reporting", "radio procedure"] },
  { code: "SOP 4.5.D", title: "Use of Mobile Data Terminals", section: "Emergency Operations", printedPage: 293, keywords: ["mdt", "mobile data terminal", "tablet", "data terminal"] },
  { code: "SOP 4.5.E", title: "Delta Dispatch Process", section: "Emergency Operations", printedPage: 294, keywords: ["delta", "delta dispatch", "priority", "life threatening"] },
  { code: "SOP 4.5.F", title: "Cancellation of Charlie or LifeFlight", section: "Emergency Operations", printedPage: 295, keywords: ["cancellation", "charlie", "lifeflight", "cancel unit"] },
  { code: "SOP 4.6", title: "Emergency Unit Response", section: "Emergency Operations", printedPage: 298, keywords: ["response", "emergency response", "driving", "unit response"] },
  { code: "SOP 4.6.A", title: "Driving of Emergency Vehicles", section: "Emergency Operations", printedPage: 300, keywords: ["driving", "emergency driving", "lights and siren", "code 3"] },
  { code: "SOP 4.6.B", title: "Prayer During HMCAS Working Hours", section: "Emergency Operations", printedPage: 304, keywords: ["prayer", "salah", "working hours", "religious"] },
  { code: "SOP 4.6.C", title: "Emergency Response and Non-Emergency Driving During Adverse Weather", section: "Emergency Operations", printedPage: 305, keywords: ["adverse weather", "rain", "fog", "sandstorm", "driving weather"] },
  { code: "SOP 4.6.D", title: "RTA While Driving Emergency Vehicles", section: "Emergency Operations", printedPage: 307, keywords: ["rta", "accident", "road traffic accident", "vehicle accident", "crash"] },
  { code: "SOP 4.7", title: "Emergency Scene Management", section: "Emergency Operations", printedPage: 310, keywords: ["scene management", "emergency scene", "scene safety"] },
  { code: "SOP 4.7.A", title: "Emergency Scene Arrival and Size-Up", section: "Emergency Operations", printedPage: 312, keywords: ["scene arrival", "size up", "scene assessment", "arrival"] },
  { code: "SOP 4.7.B", title: "Preparing a Landing Zone (LZ)", section: "Emergency Operations", printedPage: 313, keywords: ["landing zone", "lz", "helicopter", "lifeflight landing"] },
  { code: "SOP 4.7.C", title: "Scene Safety", section: "Emergency Operations", printedPage: 318, keywords: ["scene safety", "safety", "hazmat", "danger"] },
  { code: "SOP 4.8", title: "Patient Treatment and Transportation", section: "Emergency Operations", printedPage: 321, keywords: ["patient treatment", "transport", "transportation", "patient care"] },
  { code: "SOP 4.8.A", title: "Selecting Appropriate Receiving Facilities for Special Clinical Cases", section: "Emergency Operations", printedPage: 323, keywords: ["receiving facility", "hospital selection", "bypass", "destination", "special cases"] },
  { code: "SOP 4.8.B", title: "Patient Handover and Endorsement", section: "Emergency Operations", printedPage: 326, keywords: ["handover", "endorsement", "hospital handover", "isbar", "patient handover"] },
  { code: "SOP 4.8.C", title: "Communications for Verbal Orders Given Via Radio/Telephone", section: "Emergency Operations", printedPage: 330, keywords: ["verbal orders", "radio orders", "telephone orders", "medical direction"] },
  { code: "SOP 4.8.D", title: "Non-Transport and Release of Patients", section: "Emergency Operations", printedPage: 331, keywords: ["non-transport", "release", "refusal", "patient refusal", "non conveyance"] },
  { code: "SOP 4.8.E", title: "Safeguarding Patient's Valuables", section: "Emergency Operations", printedPage: 334, keywords: ["valuables", "safeguarding", "patient belongings", "property"] },
  { code: "SOP 4.8.F", title: "Management of Patients in Police Custody", section: "Emergency Operations", printedPage: 335, keywords: ["police custody", "prisoner", "detained", "custody patient"] },
  { code: "SOP 4.8.G", title: "Patient Escorts/Accompaniment", section: "Emergency Operations", printedPage: 337, keywords: ["escort", "accompaniment", "patient escort", "family member"] },
  { code: "SOP 4.8.H", title: "Rendezvous with Critical Care Paramedic", section: "Emergency Operations", printedPage: 338, keywords: ["rendezvous", "ccp", "critical care paramedic", "rdv"] },
  { code: "SOP 4.8.I", title: "Stopping the Ambulance for Clinical Procedures", section: "Emergency Operations", printedPage: 341, keywords: ["stopping", "clinical procedures", "pull over", "ambulance stop"] },
  { code: "SOP 4.8.J", title: "Emergency Blood Transfer Protocol", section: "Emergency Operations", printedPage: 342, keywords: ["blood transfer", "blood products", "emergency blood", "transfusion"] },
  { code: "SOP 4.8.K", title: "Prevention and Management of Patient Falls", section: "Emergency Operations", printedPage: 344, keywords: ["falls", "patient falls", "fall prevention", "stretcher"] },
  { code: "SOP 4.8.L", title: "Utilization of Clinical-2 Radio Channel", section: "Emergency Operations", printedPage: 345, keywords: ["clinical 2", "radio channel", "channel 2", "radio"] },
  { code: "SOP 4.8.M", title: "Cohorting of Patients Awaiting Beds at Hamad General Hospital", section: "Emergency Operations", printedPage: 347, keywords: ["cohorting", "hgh", "hamad general", "bed wait", "ramping"] },
  { code: "SOP 4.8.N", title: "Brought in Dead (BID) Process Pathway", section: "Emergency Operations", printedPage: 350, keywords: ["bid", "brought in dead", "death", "deceased", "doa"] },
  { code: "SOP 4.8.O", title: "Transporting Immunocompromised/Chemotherapy Patients", section: "Emergency Operations", printedPage: 351, keywords: ["immunocompromised", "chemotherapy", "oncology", "neutropenic", "cancer"] },
  { code: "SOP 4.8.P", title: "Transporting Patients with Suspected or Known Infectious Disease", section: "Emergency Operations", printedPage: 352, keywords: ["infectious disease", "isolation", "ppe", "infection control", "covid", "ebola"] },
  { code: "SOP 4.8.Q", title: "Vulnerable and High-Risk Patient Transportation", section: "Emergency Operations", printedPage: 353, keywords: ["vulnerable", "high risk", "special needs", "elderly", "safeguarding"] },
  { code: "SOP 4.8.R", title: "Transporting Patients with Suspected Infectious Disease in the Green Bus", section: "Emergency Operations", printedPage: 354, keywords: ["green bus", "infectious disease", "isolation transport", "bus"] },
  { code: "SOP 4.8.S", title: "Cancellation of Responding CCP Units", section: "Emergency Operations", printedPage: 356, keywords: ["cancellation", "ccp", "cancel", "stand down"] },
  { code: "SOP 4.8.T", title: "Request & Dispatch of Specialized Unit", section: "Emergency Operations", printedPage: 358, keywords: ["specialized unit", "specialist", "dispatch", "special unit"] },
  { code: "SOP 4.8.U", title: "Mental Health Transfers", section: "Emergency Operations", printedPage: 362, keywords: ["mental health", "psychiatric", "psych", "transfer", "mental health transfer"] },
  { code: "SOP 4.9", title: "Documentation", section: "Emergency Operations", printedPage: 365, keywords: ["documentation", "paperwork", "records", "epcr"] },
  { code: "SOP 4.9.A", title: "Electronic Patient Care Recording", section: "Emergency Operations", printedPage: 367, keywords: ["epcr", "electronic patient care", "patient care record", "documentation"] },
  { code: "SOP 4.9.B", title: "Reporting of Occurrences/Variations/Accidents (OVA) and Adverse Drug Reactions", section: "Emergency Operations", printedPage: 369, keywords: ["ova", "incident report", "adverse drug reaction", "adr", "occurrence"] },
  { code: "SOP 4.9.C", title: "Accurate Identification of Patients", section: "Emergency Operations", printedPage: 371, keywords: ["patient identification", "id", "wristband", "verification"] },
  { code: "SOP 4.9.D", title: "Care and Management of the Electronic Patient Care Record Platform", section: "Emergency Operations", printedPage: 372, keywords: ["epcr", "platform", "system", "electronic record"] },
  { code: "SOP 4.10", title: "Major Incident Response (MIR)", section: "Emergency Operations", printedPage: 375, keywords: ["major incident", "mir", "mass casualty", "mci", "disaster"] },
  { code: "SOP 4.10.A", title: "MIR First Unit on Scene", section: "Emergency Operations", printedPage: 377, keywords: ["major incident", "first on scene", "mir", "initial response"] },
  { code: "SOP 4.10.B", title: "Major Incident Scene Setup", section: "Emergency Operations", printedPage: 380, keywords: ["scene setup", "major incident", "casualty clearing", "mir setup"] },
  { code: "SOP 4.10.C", title: "Decontamination (Decon) Setup, Response and Mitigation", section: "Emergency Operations", printedPage: 387, keywords: ["decon", "decontamination", "hazmat", "cbrn", "chemical"] },

  // ── SOP 4.11: LifeFlight ─────────────────────────────────────────────────────
  { code: "SOP 4.11", title: "LifeFlight", section: "LifeFlight", printedPage: 398, keywords: ["lifeflight", "helicopter", "air ambulance", "hems"] },
  { code: "SOP 4.11.A", title: "LifeFlight Operations", section: "LifeFlight", printedPage: 398, keywords: ["lifeflight", "operations", "helicopter", "hems"] },
  { code: "SOP 4.11.A.1", title: "Daily LifeFlight Operations", section: "LifeFlight", printedPage: 400, keywords: ["daily operations", "lifeflight", "helicopter", "shift"] },
  { code: "SOP 4.11.A.2", title: "Helicopter Operations at Hamad General Hospital", section: "LifeFlight", printedPage: 402, keywords: ["hgh", "hamad general", "helicopter", "helipad"] },
  { code: "SOP 4.11.A.3", title: "Helicopter Operating Sites", section: "LifeFlight", printedPage: 403, keywords: ["helicopter sites", "operating sites", "lz", "helipad"] },
  { code: "SOP 4.11.A.4", title: "Flight Following", section: "LifeFlight", printedPage: 404, keywords: ["flight following", "tracking", "helicopter tracking"] },
  { code: "SOP 4.11.A.5", title: "LifeFlight Crew Configuration & Scheduling", section: "LifeFlight", printedPage: 411, keywords: ["crew", "scheduling", "lifeflight crew", "configuration"] },
  { code: "SOP 4.11.A.6", title: "General & Clinical Responsibilities during a LifeFlight Shift", section: "LifeFlight", printedPage: 413, keywords: ["lifeflight", "responsibilities", "clinical duties", "shift duties"] },
  { code: "SOP 4.11.A.7", title: "Deceased Patient on LifeFlight", section: "LifeFlight", printedPage: 414, keywords: ["deceased", "death", "lifeflight", "in flight death"] },
  { code: "SOP 4.11.A.8", title: "Non-Emergency and Ad Hoc LifeFlight Missions", section: "LifeFlight", printedPage: 415, keywords: ["non-emergency", "ad hoc", "planned", "lifeflight mission"] },
  { code: "SOP 4.11.A.9", title: "Leave and Duty Exchange on Lifeflight", section: "LifeFlight", printedPage: 418, keywords: ["leave", "duty exchange", "lifeflight", "swap"] },
  { code: "SOP 4.11.A.10", title: "Management of Bariatric Patients by LifeFlight", section: "LifeFlight", printedPage: 420, keywords: ["bariatric", "obese", "weight", "lifeflight bariatric"] },
  { code: "SOP 4.11.A.11", title: "LifeFlight Hot Loading Procedure", section: "LifeFlight", printedPage: 422, keywords: ["hot loading", "hot offload", "rotors running", "lifeflight"] },
  { code: "SOP 4.11.A.12", title: "LifeFlight Configuration & Passenger Safety", section: "LifeFlight", printedPage: 424, keywords: ["configuration", "passenger safety", "lifeflight", "helicopter safety"] },
  { code: "SOP 4.11.A.13", title: "Latex Allergy Precautions", section: "LifeFlight", printedPage: 427, keywords: ["latex", "allergy", "latex allergy", "gloves"] },
  { code: "SOP 4.11.A.14", title: "LifeFlight Offshore Activation and Operations", section: "LifeFlight", printedPage: 428, keywords: ["offshore", "lifeflight", "offshore activation", "maritime"] },
  { code: "SOP 4.11.A.15", title: "Lifeflight Self Dispatch", section: "LifeFlight", printedPage: 432, keywords: ["self dispatch", "lifeflight", "self activation"] },
  { code: "SOP 4.11.B", title: "LifeFlight Health & Safety", section: "LifeFlight", printedPage: 434, keywords: ["health safety", "lifeflight", "crew safety"] },
  { code: "SOP 4.11.B.1", title: "Use of Medical Crew Restraints", section: "LifeFlight", printedPage: 436, keywords: ["restraints", "harness", "seatbelt", "crew restraints"] },
  { code: "SOP 4.11.B.2", title: "Physical Fitness & Assessment Procedure", section: "LifeFlight", printedPage: 437, keywords: ["physical fitness", "assessment", "fitness test", "lifeflight fitness"] },
  { code: "SOP 4.11.B.3", title: "Fitness to Fly", section: "LifeFlight", printedPage: 439, keywords: ["fitness to fly", "medical fitness", "flying", "aeromedical"] },
  { code: "SOP 4.11.B.4", title: "Cleaning of LifeFlight (LF) Helicopters", section: "LifeFlight", printedPage: 442, keywords: ["helicopter cleaning", "lifeflight", "aircraft cleaning", "decontamination"] },
  { code: "SOP 4.11.C", title: "LifeFlight Equipment", section: "LifeFlight", printedPage: 445, keywords: ["lifeflight equipment", "helicopter equipment", "medical equipment"] },
  { code: "SOP 4.11.C.1", title: "LifeFlight Personal Protective Equipment", section: "LifeFlight", printedPage: 447, keywords: ["ppe", "lifeflight ppe", "helmet", "flight suit", "personal protective"] },
  { code: "SOP 4.11.C.2", title: "Care of Personal Protective Equipment", section: "LifeFlight", printedPage: 450, keywords: ["ppe care", "equipment maintenance", "flight suit", "helmet care"] },
  { code: "SOP 4.11.C.3", title: "Medical Equipment, Consumables and Asset Management", section: "LifeFlight", printedPage: 453, keywords: ["equipment", "consumables", "asset management", "stock"] },

  // ── SOP 5: Retrieval Services ────────────────────────────────────────────────
  { code: "SOP 5.1", title: "Retrieval Services (RS): General", section: "Retrieval Services", printedPage: 457, keywords: ["retrieval", "retrieval services", "rs", "sop 5"] },
  { code: "SOP 5.1.A", title: "Retrieval Services Driving", section: "Retrieval Services", printedPage: 459, keywords: ["retrieval", "driving", "retrieval driving"] },
  { code: "SOP 5.1.B", title: "Management of Emergency Patients by Retrieval Units", section: "Retrieval Services", printedPage: 460, keywords: ["retrieval", "emergency patients", "critical patient"] },
  { code: "SOP 5.1.C", title: "Airport Operations", section: "Retrieval Services", printedPage: 462, keywords: ["airport", "operations", "hamad airport", "hia", "airside"] },
  { code: "SOP 5.2", title: "Scheduled Ambulance Service (SAS)", section: "Retrieval Services", printedPage: 465, keywords: ["sas", "scheduled ambulance", "planned transport", "non-emergency"] },
  { code: "SOP 5.2.A", title: "Scheduled Ambulance Service (SAS) Supervisor Duties", section: "Retrieval Services", printedPage: 467, keywords: ["sas", "supervisor", "scheduled ambulance", "duties"] },
  { code: "SOP 5.3", title: "Inter-Facility Transport", section: "Retrieval Services", printedPage: 471, keywords: ["inter-facility", "transfer", "hospital transfer", "ift"] },
  { code: "SOP 5.3.A", title: "Emergency Transfers from HGH ED to Heart Hospital", section: "Retrieval Services", printedPage: 473, keywords: ["hgh", "heart hospital", "emergency transfer", "cardiac transfer"] },
  { code: "SOP 5.3.B", title: "Paediatric Emergency Centre (PEC) Transfers", section: "Retrieval Services", printedPage: 475, keywords: ["pec", "paediatric", "sidra", "paediatric transfer"] },
  { code: "SOP 5.3.C", title: "Neonatal Intensive Care Unit (NICU) Transfers", section: "Retrieval Services", printedPage: 477, keywords: ["nicu", "neonatal", "newborn", "nicu transfer", "premature"] },
  { code: "SOP 5.3.E", title: "Ambulatory Patient Transport to Carry-Out Interfacility Transfers", section: "Retrieval Services", printedPage: 479, keywords: ["ambulatory", "interfacility", "transfer", "walking patient"] },
  { code: "SOP 5.4", title: "Retrieval Services", section: "Retrieval Services", printedPage: 484, keywords: ["retrieval services", "rs", "critical care transfer"] },
  { code: "SOP 5.4.A", title: "Retrieval Services Operations", section: "Retrieval Services", printedPage: 484, keywords: ["retrieval", "operations", "retrieval ops"] },
  { code: "SOP 5.4.A.2", title: "High Acuity Adult Transfers", section: "Retrieval Services", printedPage: 486, keywords: ["high acuity", "adult transfer", "critical care", "icu transfer"] },
  { code: "SOP 5.4.A.3.2", title: "Commercial Flight Operations: Repatriation to Qatar", section: "Retrieval Services", printedPage: 488, keywords: ["commercial flight", "repatriation", "aeromedical", "qatar repatriation"] },
  { code: "SOP 5.4.A.8", title: "Extracorporeal Membrane Oxygenation (ECMO) Patient Transfers", section: "Retrieval Services", printedPage: 496, keywords: ["ecmo", "ecpr", "transfer", "extracorporeal"] },
  { code: "SOP 5.4.A.9", title: "Aeromedical Transport of Bariatric Patients Using QEAF Aircraft", section: "Retrieval Services", printedPage: 498, keywords: ["bariatric", "aeromedical", "qeaf", "aircraft", "obese transport"] },
  { code: "SOP 5.4.A.10", title: "Aeromedical Logistic Planning Considerations", section: "Retrieval Services", printedPage: 500, keywords: ["aeromedical", "logistics", "planning", "flight planning"] },
  { code: "SOP 5.4.A.13", title: "Emergency Ration Packs", section: "Retrieval Services", printedPage: 504, keywords: ["ration packs", "emergency rations", "food", "retrieval"] },
  { code: "SOP 5.4.E", title: "Retrieval Services Quality Management & Quality Improvement", section: "Retrieval Services", printedPage: 506, keywords: ["quality management", "qi", "retrieval quality", "audit"] },
  { code: "SOP 5.4.E.1", title: "Retrieval Service Operational Currency", section: "Retrieval Services", printedPage: 508, keywords: ["operational currency", "currency", "competency", "retrieval competency"] },
  { code: "SOP 5.4.F", title: "Retrieval Services Quality Assurance & Improvement", section: "Retrieval Services", printedPage: 517, keywords: ["quality assurance", "qa", "improvement", "retrieval"] },
  { code: "SOP 5.4.F.4", title: "Management and Administration of Blood Products", section: "Retrieval Services", printedPage: 519, keywords: ["blood products", "blood", "transfusion", "plasma", "prbc"] },
  { code: "SOP 5.4.F.6", title: "Patient Handover & Endorsement", section: "Retrieval Services", printedPage: 521, keywords: ["handover", "endorsement", "retrieval handover", "patient handover"] },
  { code: "SOP 5.4.G", title: "Retrieval Service Equipment", section: "Retrieval Services", printedPage: 524, keywords: ["retrieval equipment", "equipment", "retrieval kit"] },
  { code: "SOP 5.4.G.1", title: "Use of the ParAid Stretcher", section: "Retrieval Services", printedPage: 526, keywords: ["paraid", "stretcher", "scoop", "retrieval stretcher"] },
  { code: "SOP 5.4.G.2", title: "Securing of Equipment During Transfer", section: "Retrieval Services", printedPage: 528, keywords: ["securing equipment", "equipment securing", "strapping", "transfer"] },
  { code: "SOP 5.4.G.3", title: "Cold Chain Medication Use and Sign Out by RS CCPs & Doctors", section: "Retrieval Services", printedPage: 529, keywords: ["cold chain", "medications", "temperature controlled", "blood products"] },
  { code: "SOP 5.4.G.4", title: "Controlled Medicines Management by RS Critical Care Paramedics & Medical Doctors", section: "Retrieval Services", printedPage: 533, keywords: ["controlled medicines", "ccp", "doctor", "controlled drugs", "retrieval"] },

  // ── SOP 6: Events & Emergency Planning ──────────────────────────────────────
  { code: "SOP 6", title: "Events & Emergency Planning", section: "Events Emergency Planning", printedPage: 536, keywords: ["events", "emergency planning", "sop 6"] },
  { code: "SOP 6.1", title: "Staffing of Events and Sealine Camping Season", section: "Events Emergency Planning", printedPage: 538, keywords: ["events", "staffing", "sealine", "camping", "coverage"] },
  { code: "SOP 6.2", title: "Adverse Weather Preparedness, Response And Recovery", section: "Events Emergency Planning", printedPage: 541, keywords: ["adverse weather", "sandstorm", "flood", "emergency plan"] },
  { code: "SOP 6.3", title: "Drill/Event Planning & Management", section: "Events Emergency Planning", printedPage: 545, keywords: ["drill", "exercise", "planning", "event management"] },

  // ── SOP 7: Training ──────────────────────────────────────────────────────────
  { code: "SOP 7", title: "Training", section: "Training", printedPage: 550, keywords: ["training", "education", "sop 7"] },
  { code: "SOP 7.1", title: "Orientation of All HMCAS Ambulance Paramedic and Critical Care Paramedic Staff", section: "Training", printedPage: 552, keywords: ["orientation", "induction", "onboarding", "new staff"] },
  { code: "SOP 7.2", title: "Annual Training Requirements and Minimum Patient Facing Hours for APs and CCPs", section: "Training", printedPage: 555, keywords: ["annual training", "training requirements", "patient hours", "cpd"] },
  { code: "SOP 7.3", title: "Required Safety Courses for All HMCAS Staff", section: "Training", printedPage: 557, keywords: ["safety courses", "mandatory training", "required courses"] },
  { code: "SOP 7.4", title: "Reporting of Compliance with Mandatory Clinical Training", section: "Training", printedPage: 559, keywords: ["compliance", "reporting", "mandatory training", "compliance reporting"] },
  { code: "SOP 7.5", title: "Scheduling of Core HMCAS CPD Courses for APs and CCPs", section: "Training", printedPage: 560, keywords: ["cpd", "scheduling", "courses", "continuing education"] },
  { code: "SOP 7.6", title: "Driver Training", section: "Training", printedPage: 561, keywords: ["driver training", "driving", "vehicle training", "edriving"] },
  { code: "SOP 7.7", title: "Return to Clinical Practice Following a Break in Service", section: "Training", printedPage: 562, keywords: ["return to practice", "break in service", "reorientation", "clinical return"] },
  { code: "SOP 7.9", title: "Maintaining Licensure with DHP and Privileging", section: "Training", printedPage: 566, keywords: ["dhp", "license", "licensure", "privileging", "registration"] },

  // ── SOP 8: Clinical Desk ─────────────────────────────────────────────────────
  { code: "SOP 8", title: "Clinical Desk", section: "Clinical Desk", printedPage: 570, keywords: ["clinical desk", "sop 8"] },
  { code: "SOP 8.4", title: "Clinical Desk Process Flows", section: "Clinical Desk", printedPage: 572, keywords: ["clinical desk", "process flow", "workflow"] },
  { code: "SOP 8.5", title: "Clinical Desk Onboarding and Currency", section: "Clinical Desk", printedPage: 574, keywords: ["clinical desk", "onboarding", "currency", "competency"] },
  { code: "SOP 8.6", title: "Clinical Desk Daily Operations", section: "Clinical Desk", printedPage: 581, keywords: ["clinical desk", "daily operations", "operations"] },
  { code: "SOP 8.7", title: "Clinical Desk Phone Call Management", section: "Clinical Desk", printedPage: 587, keywords: ["clinical desk", "phone", "call management"] },
  { code: "SOP 8.8", title: "Hospital Pre-Arrival Notification", section: "Clinical Desk", printedPage: 592, keywords: ["pre-arrival", "notification", "hospital notification", "handover pre-alert"] },
  { code: "SOP 8.9", title: "Transfer Escalation to the Clinical Desk", section: "Clinical Desk", printedPage: 596, keywords: ["transfer", "escalation", "clinical desk", "escalation"] },

  // ── Appendices ───────────────────────────────────────────────────────────────
  { code: "Appendix 1.2-1", title: "Uniform Entitlement", section: "Appendix", printedPage: 603, keywords: ["uniform", "entitlement", "clothing", "apparel"] },
  { code: "Appendix 1.2-2", title: "HMCAS Rank Insignia", section: "Appendix", printedPage: 610, keywords: ["rank", "insignia", "rank insignia", "uniform rank"] },
  { code: "Appendix 1.2-3", title: "Washing Instructions", section: "Appendix", printedPage: 611, keywords: ["washing", "uniform care", "laundry"] },
  { code: "Appendix 1.2-4", title: "Uniform Request Form", section: "Appendix", printedPage: 612, keywords: ["uniform request", "form", "uniform form"] },
  { code: "Appendix 1.2-5", title: "End of Service Uniform Checklist", section: "Appendix", printedPage: 613, keywords: ["end of service", "uniform return", "checklist"] },
  { code: "Appendix 3.14", title: "List of Health Facilities for MPDS Protocols 33 & 37", section: "Appendix", printedPage: 614, keywords: ["health facilities", "mpds", "hospitals", "facilities list"] },
  { code: "Appendix 3.22", title: "Inter-Facility Patient Transfers", section: "Appendix", printedPage: 620, keywords: ["inter-facility", "transfers", "ift", "hospital list"] },
  { code: "Appendix 3.24", title: "NCC-LF Offshore Checklist", section: "Appendix", printedPage: 621, keywords: ["offshore", "checklist", "ncc", "lifeflight offshore"] },
  { code: "Appendix 4.4.A", title: "Emergency Unit Distribution – Current Hub and Spoke Locations", section: "Appendix", printedPage: 622, keywords: ["hub spoke", "locations", "stations", "distribution map"] },
  { code: "Appendix 4.4.B", title: "Map of Current Hub and Spoke Doha", section: "Appendix", printedPage: 625, keywords: ["map", "doha", "hub spoke", "stations doha"] },
  { code: "Appendix 4.4.C", title: "Map of Current Hub and Spoke Qatar", section: "Appendix", printedPage: 626, keywords: ["map", "qatar", "hub spoke", "stations qatar"] },
  { code: "Appendix 4.4.D", title: "Unit Availability Escalation Procedures", section: "Appendix", printedPage: 627, keywords: ["unit availability", "escalation", "shortage", "coverage"] },
  { code: "Appendix 4.7.B-1", title: "Designated Helicopter Operating Sites", section: "Appendix", printedPage: 628, keywords: ["helicopter sites", "operating sites", "helipad", "lz list"] },
  { code: "Appendix 4.7.B-2", title: "Important Aircraft Safety Rules", section: "Appendix", printedPage: 630, keywords: ["aircraft safety", "helicopter safety", "safety rules"] },
  { code: "Appendix 4.8.A", title: "Trauma Bypass Criteria", section: "Appendix", printedPage: 631, keywords: ["trauma bypass", "bypass criteria", "major trauma", "hospital bypass"] },
  { code: "Appendix 4.8.M", title: "Key Roles and Functions of Staff Cohorting", section: "Appendix", printedPage: 632, keywords: ["cohorting", "roles", "staff roles", "hgh cohorting"] },
  { code: "Appendix 4.8.N", title: "Brought in Dead (BID) Admission Process Pathway", section: "Appendix", printedPage: 633, keywords: ["bid", "brought in dead", "death pathway", "deceased"] },
  { code: "Appendix 4.11.A.2", title: "LifeFlight HOTEL ECHO Helipad Activation Process", section: "Appendix", printedPage: 634, keywords: ["hotel echo", "helipad", "lifeflight", "hgh helipad"] },
  { code: "Appendix 5.4.A.3.2-1", title: "Medical Information Form (MEDIF)", section: "Appendix", printedPage: 635, keywords: ["medif", "medical information form", "commercial flight", "aeromedical form"] },
  { code: "Appendix 5.4.A.3.2-2", title: "Medical Attaché Request Form", section: "Appendix", printedPage: 641, keywords: ["medical attache", "request form", "retrieval"] },
  { code: "Appendix 5.4.A.3.2-3", title: "Medical Team Member Emergency Contact Form", section: "Appendix", printedPage: 642, keywords: ["emergency contact", "team member", "form"] },
  { code: "Appendix 5.4.A.3.2-4", title: "Mission Tasking Form", section: "Appendix", printedPage: 643, keywords: ["mission tasking", "form", "retrieval tasking"] },
  { code: "Appendix 5.4.A.3.2-7", title: "Acknowledgement of Agreement on High Risk Travel", section: "Appendix", printedPage: 644, keywords: ["high risk travel", "agreement", "acknowledgement"] },
  { code: "Appendix 8.8.1", title: "Hospital Pre-Arrival Notification Process", section: "Appendix", printedPage: 645, keywords: ["pre-arrival", "notification", "hospital", "pre-alert"] },
  { code: "Appendix 8.9.A", title: "Clinical Triage of Interfacility Transfers: Schedule and Immediate Process Flow", section: "Appendix", printedPage: 646, keywords: ["triage", "interfacility", "transfer triage", "process flow"] },
  { code: "Appendix 8.9.B", title: "Clinical Desk Transfer Triage Matrix", section: "Appendix", printedPage: 647, keywords: ["triage matrix", "transfer", "clinical desk", "matrix"] },
  { code: "Appendix 8.9.C", title: "PHCC Escalation Additional Questions", section: "Appendix", printedPage: 648, keywords: ["phcc", "escalation", "questions"] },
];

export function searchSopEntries(query: string): SopEntry[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  return SOP_ENTRIES.filter((entry) => {
    return (
      entry.code.toLowerCase().includes(q) ||
      entry.title.toLowerCase().includes(q) ||
      entry.section.toLowerCase().includes(q) ||
      entry.keywords.some((k) => k.includes(q))
    );
  }).slice(0, 6);
}
